### ISSUE TITLE
CPU freq showing 0

### ISSUE THREAD

**Issue by sgrayban** [avafinger/htop_2.2.2-amd64#1]
![image](https://user-images.githubusercontent.com/1351910/92665740-25319000-f2bc-11ea-8d10-2db9f891da7e.png)

As you can see even with my amd64 the freq is still not registering. Can this be fixed?

**Comment by avafinger** [comment]
Please, see the section:
https://github.com/avafinger/htop_2.2.2-amd64#handlers

Cpu Frequency depends on Kernel config and DTB, find the path and update the handler.

**Comment by avafinger** [comment]
Note you have new Core meters if kernel has the options (INTEL) :

![cpufreq](https://user-images.githubusercontent.com/16623039/92732889-6c1b9600-f34d-11ea-918e-3b93bf22b7d3.png)

**Comment by stulluk** [comment]
For the people who wants simple answer, I fixed this issue by editing $HOME/.config/htop/htoprc file, and editing this line:

CpuTemp_handler=/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:16/ATK0110:00/hwmon/hwmon0/temp1_input

My system :
```
stulluk ~ $  inxi
CPU: 6-Core AMD FX-6300 (-MCP-) speed/min/max: 1406/1400/3500 MHz Kernel: 5.4.0-58-generic x86_64 Up: 1h 09m 
Mem: 1764.6/11963.9 MiB (14.7%) Storage: 1.36 TiB (54.4% used) Procs: 274 Shell: bash 4.4.20 inxi: 3.0.32 
stulluk ~ $  inxi -M
Machine:   Type: Desktop Mobo: ASUSTeK model: M5A78L-M LX3 v: Rev X.0x serial: <root required> BIOS: American Megatrends 
           v: 1401 date: 05/05/2016 
stulluk ~ $
```

On some ASUS Mainboards there is a kernel driver called ATK0110 . This driver provides ACPI Hardware monitoring interface for ASUS mainboards.

Alternatively, I could write:
CpuTemp_handler=/sys/class/hwmon/hwmon0/temp1_input 

(Tested, working)

You can find your temperature sensors under /sys/class/hwmon/ directory.

Thank you @avafinger , it is an amazing improvement to default htop !

**Comment by avafinger** [comment]
No more activity, closing for now.
